application: alumni-outcomes
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /.*
  script: alumni-outcomes.app

libraries:
- name: jinja2
  version: latest

- name: django
  version: latest